services:
  - type: web
    name: oksystem-aircon-backend
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.vercel.app
      - key: ADMIN_KEY
        sync: false
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_PORT
        value: 3306
      - key: MYSQL_DATABASE
        value: oksystem
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false


